### PR TITLE
add comments to every article

### PR DESCRIPTION
**Pull request by nldblanch**

### CODE REVIEW

**Comment by nc-niamh-smith** [comment]
When I'm trying to navigate to your /articles/1, I'm getting an uncaught promise error in the console. Upon refreshing, then the data comes through eventually, but it takes its time - and for some reason the isLoading wasn't working for me, _but_ I can see by your code it is definitely there, so make sure you verify that it is definitely working. 

Another thing to consider is that your app looks _great_ on a smaller screen, but when the screen is dragged out to full size, it _is_ responsive, but it is not styled too well. Think about the root element of size that has been set and use that for your sizing of images in particular.

**Comment by nldblanch** [comment]
Thanks Niamh, I'm definitely going to go over the screen size - I know it looks pretty bad and was going to do that at some point today

**Comment by nldblanch** [comment]
navigating to articles/1 isn't rejecting in my console. Are you able to send me a screenshot of the error?

**Comment by nc-niamh-smith** [comment]
It works eventually - I think it's an API issue (just taking its time! They are free APIs!) but the big issue is the isLoading not working! Use your inspect to have a look at slowing down your network time to see whether it is working for you (happy to accept that it might be a me issue!)

**Pull request merged**
